### ISSUE TITLE
Docker publishing CI job failing

### ISSUE THREAD

**Issue by collinarnett** [acryldata/datahub-actions#119]
https://github.com/acryldata/datahub-actions/actions/runs/9423463832/job/25961896536

**Comment by cseatjc** [comment]
Would appreciate this looked at as there is a vuln in v0.0.15 and we would like to use newest version

**Comment by cseatjc** [comment]
Are there any updates here?

**Comment by hsheth2** [comment]
Fixed by https://github.com/acryldata/datahub-actions/commit/b1f05293665a78f5cfb0241205bdceebbdffd861 - 0.0.18 was released yesterday.
