### ISSUE TITLE
datahub actions conflict with data acryl-datahub 0.9

### ISSUE THREAD

**Issue by Plipala** [acryldata/datahub-actions#49]
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of acryl-datahub to determine which version is compatible with other requirements. This could take a while.

The conflict is caused by:
    The user requested avro-gen3==0.7.6
     acryl-datahub 0.9.0.3 depends on avro-gen3==0.7.6
    acryl-datahub-actions 0.0.8 depends on avro-gen3==0.7.4

**Comment by hsheth2** [comment]
Thanks for filing this issue - looks like we've declared our dependencies in this repo incorrectly
