### ISSUE TITLE
Add support for SASL/GSSAPI properties in Action Framework

### ISSUE THREAD

**Issue by dianadujing** [acryldata/datahub-actions#73]
Hi there,

In guide of "[Configuring Kafka in DataHub](https://datahubproject.io/docs/how/kafka-config/)", there is detailed elaboration of how to set SASL/GSSAPI properties for Datahub core. However, there is no such configuration in Action Framework:
[https://github.com/acryldata/datahub-actions/blob/main/datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py#L124](https://github.com/acryldata/datahub-actions/blob/main/datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py#L124)

Is there any plan to enable same configuration settings for Action Framework?

Thanks

**Comment by upendrao** [comment]
I have similar issue especially with lack of support for [conumer_config](https://github.com/acryldata/datahub-actions/blob/792a8a8a7e33959ec3ebe95a3dde030438298f8a/datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py#L137)
I had to workaround by supplying my own copy of default `executor.yaml` file with all the consumer config to be able to use datahub-actions unless I am seriously missing some documentation here explaining a way out.
