### ISSUE TITLE
adding mysql-connector-python to the list of pip packages inside venv-mysql

### ISSUE THREAD

**Issue by justmike1** [acryldata/datahub-actions#95]
Hey, 

I am using datahub-actions to ingest my MySQL and I have noticed you guys are using pymysql as the default connector for mysql integration, this is causing problems regarding connectivity and ssl, the fix was to use the feature:

`sqlalchemy_uri`: mysql+mysqlconnector://user:password@x.x.x.x:3306/smth_data

and to exec to the datahub-actions pod, activate the venv-mysql, and to manually install the package:

mysql-connector-python 8.1.0

**Comment by hsheth2** [comment]
@justmike1 I missed this one. I don't think it makes sense for `mysql` to require both connector types, but we could do something similar to what we've done for `mssql` and `mssql-odbc` to have two possible dependency sets for the same connector.
